> data load, data save as pickle

https://pytorch-geometric-temporal.readthedocs.io/en/latest/_modules/index.html



- GNAR warning message 위한 uppressWarnings 

In [248]:
my_list = [[] for _ in range(15)]
another_list = list(range(10,20))
my_list[10] = another_list

# Import

In [1]:
import numpy as np

In [2]:
import json
import urllib

In [3]:
def load_data(fname):
    with open(fname, 'rb') as outfile:
        data_dict = pickle.load(outfile)
    return data_dict

In [4]:
def save_data(data_dict,fname):
    with open(fname,'wb') as outfile:
        pickle.dump(data_dict,outfile)

In [5]:
import pickle

In [ ]:
save_data(df_gnar, './data/EnglandCovid_gnar_randomly_by_rate.pkl')

In [ ]:
load_data('./data/GNAR_stgcn_randomly_by_rate.pkl')

```
!git add .
!git commit -m .
!git push 
!quarto publish --no-browser --no-prompt 
```

In [16]:
_data = load_data('./_data/fivenodes.pkl')

In [17]:
import torch

In [18]:
_edges = torch.tensor(_data['edges']).nonzero().tolist()
_FX = _data['f'].tolist()
_node_ids = {'node1':0, 'node2':1, 'node3':2, 'node4':3, 'node5':4} 

In [19]:
data_dict = {'edges':_edges, 'node_ids':_node_ids, 'FX':_FX}
#data_dict = itstgcn.load_data('./data/fivenodes.pkl')

In [23]:
data_dict['edges']

[[0, 3],
 [0, 4],
 [1, 2],
 [1, 3],
 [2, 1],
 [2, 3],
 [3, 0],
 [3, 1],
 [3, 2],
 [4, 0]]

In [24]:
np.array(data_dict['edges']).shape

(10, 2)

In [21]:
data_dict['node_ids'] # node 수

{'node1': 0, 'node2': 1, 'node3': 2, 'node4': 3, 'node5': 4}

In [22]:
np.array(data_dict['FX']).shape # time by node

(200, 5)

In [17]:
save_data(data_dict, './data/fivenodes.pkl')

In [ ]:
load_data('./data/GNAR_stgcn_randomly_by_rate.pkl')

## ChickenpoxDatasetLoader

Chickenpox Hungary

- A spatiotemporal dataset about the officially reported cases of chickenpox in Hungary. The nodes are counties and edges describe direct neighbourhood relationships. The dataset covers the weeks between 2005 and 2015 without missingness.

데이터정리 

- T = 519
- N = 20 # number of nodes 
- E = 102 # edges 
- $f(v,t)$의 차원? (1,)
- 시간에 따라서 Number of nodes가 변하는지? False
- 시간에 따라서 Number of nodes가 변하는지? False
- X: (20,4) (N,4), $f(v,t_0),f(v,t_1),f(v,t_2),f(v,t_3)$
- y: (20,) (N,), $f(v,t_4)$
- 예제코드적용가능여부: Yes

`-` Nodes : `20`

- vertices are counties

`-`Edges : `102`

- edges are neighbourhoods

`-` Time : `519`

- between 2004 and 2014
- per weeks

In [453]:
from torch_geometric_temporal.dataset import ChickenpoxDatasetLoader
loader1 = ChickenpoxDatasetLoader()

In [454]:
a = loader1.get_dataset()

In [455]:
np.array(a.edge_index).shape

(2, 102)

In [456]:
np.array(a.edge_weight).shape

(102,)

In [457]:
a.edge_weight

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## PedalMeDatasetLoader

Pedal Me Deliveries

- A dataset about the number of weekly bicycle package deliveries by Pedal Me in London during 2020 and 2021. Nodes in the graph represent geographical units and edges are proximity based mutual adjacency relationships.

데이터정리 

- T = 33
- V = 지역의 집합
- N = 15 # number of nodes 
- E = 225 # edges 
- $f(v,t)$의 차원? (1,) #  number of deliveries
- 시간에 따라서 N이 변하는지? False
- 시간에 따라서 E가 변하는지? False
- X: (15,4) (N,4), $f(v,t_0),f(v,t_1),f(v,t_2),f(v,t_3)$
- y: (15,) (N,), $f(v,t_4)$
- 예제코드적용가능여부: Yes

`-` Nodes : `15`

- vertices are localities

`-`Edges : `225`

- edges are spatial_connections

`-` Time : `33`

- between 2020 and 2021
- per weeks

In [458]:
from torch_geometric_temporal.dataset import PedalMeDatasetLoader
loader2 = PedalMeDatasetLoader()

In [459]:
a = loader2.get_dataset()

In [460]:
np.array(a.edge_index).shape

(2, 225)

In [461]:
np.array(a.edge_weight).shape

(225,)

## WikiMathsDatasetLoader

Wikipedia Math

- Contains Wikipedia pages about popular mathematics topics and edges describe the links from one page to another. Features describe the number of daily visits between 2019 and 2021 March.

데이터정리 

- T = 730
- V = 위키피디아 페이지
- N = 1068 # number of nodes 
- E = 27079 # edges 
- $f(v,t)$의 차원? (1,) # 해당페이지를 유저가 방문한 횟수 
- 시간에 따라서 N이 변하는지? False
- 시간에 따라서 E가 변하는지? False
- X: (1068,8) (N,8), $f(v,t_0),f(v,t_1),f(v,t_2),f(v,t_3),f(v,t_4),f(v,t_5),f(v,t_6),f(v,t_7)$
- y: (1068,) (N,), $f(v,t_8)$
- 예제코드적용가능여부: Yes

`-` Nodes : `1068`

- vertices are Wikipedia pages

`-`Edges : `27079`

- edges are links between them

`-` Time : `730`

- Wikipedia pages between March 16th 2019 and March 15th 2021
- per weeks

In [437]:
from torch_geometric_temporal.dataset import WikiMathsDatasetLoader
loader3 = WikiMathsDatasetLoader()

In [438]:
a = loader3.get_dataset()

In [439]:
np.array(a.edge_index).shape

(2, 27079)

In [440]:
np.array(a.edge_weight).shape

(27079,)

## WindmillOutputLargeDatasetLoader

Hourly energy output of windmills from a European country for more than 2 years. Vertices represent 319 windmills and weighted edges describe the strength of relationships. The target variable allows for regression tasks.

데이터정리 

- T = 17470
- V = 풍력발전소
- N = 319 # number of nodes 
- E = 101761 = N^2 # edges 
- $f(v,t)$의 차원? (1,) # Hourly energy output 
- 시간에 따라서 N이 변하는지? False
- 시간에 따라서 E가 변하는지? False
- X: (319,4) (N,4), $f(v,t_0),f(v,t_1),f(v,t_2),f(v,t_3)$
- y: (319,) (N,), $f(v,t_4)$
- 예제코드적용가능여부: Yes

`-` Nodes : `319`

- vertices represent 319 windmills

`-`Edges : `101761`

- weighted edges describe the strength of relationships.

`-` Time : `17470`

- more than 2 years

In [449]:
from torch_geometric_temporal.dataset import WindmillOutputLargeDatasetLoader
loader4 = WindmillOutputLargeDatasetLoader()

In [450]:
a = loader4.get_dataset()

In [451]:
np.array(a.edge_index).shape

(2, 101761)

In [452]:
np.array(a.edge_weight).shape

(101761,)

## WindmillOutputMediumDatasetLoader

Hourly energy output of windmills from a European country for more than 2 years. Vertices represent 26 windmills and weighted edges describe the strength of relationships. The target variable allows for regression tasks.



데이터정리 

- T = 17470
- V = 풍력발전소
- N = 319 # number of nodes 
- E = 101761 = N^2 # edges 
- $f(v,t)$의 차원? (1,) # Hourly energy output 
- 시간에 따라서 N이 변하는지? False
- 시간에 따라서 E가 변하는지? False
- X: (319,4) (N,4), $f(v,t_0),f(v,t_1),f(v,t_2),f(v,t_3)$
- y: (319,) (N,), $f(v,t_4)$
- 예제코드적용가능여부: Yes

`-` Nodes : `26`

- vertices represent 26 windmills

`-`Edges : `225`

- weighted edges describe the strength of relationships

`-` Time : `676`

-  more than 2 years

In [441]:
from torch_geometric_temporal.dataset import WindmillOutputMediumDatasetLoader
loader5 = WindmillOutputMediumDatasetLoader()

In [442]:
a = loader5.get_dataset()

In [443]:
np.array(a.edge_index).shape

(2, 676)

In [444]:
np.array(a.edge_weight).shape

(676,)

## WindmillOutputSmallDatasetLoader

Hourly energy output of windmills from a European country for more than 2 years. Vertices represent 11 windmills and weighted edges describe the strength of relationships. The target variable allows for regression tasks.

데이터정리 

- T = 17470
- V = 풍력발전소
- N = 319 # number of nodes 
- E = 101761 = N^2 # edges 
- $f(v,t)$의 차원? (1,) # Hourly energy output 
- 시간에 따라서 N이 변하는지? False
- 시간에 따라서 E가 변하는지? False
- X: (319,4) (N,4), $f(v,t_0),f(v,t_1),f(v,t_2),f(v,t_3)$
- y: (319,) (N,), $f(v,t_4)$
- 예제코드적용가능여부: Yes

`-` Nodes : `11`

- vertices represent 11 windmills

`-`Edges : `121`

- weighted edges describe the strength of relationships

`-` Time : `17470`

- more than 2 years

In [445]:
from torch_geometric_temporal.dataset import WindmillOutputSmallDatasetLoader
loader6 = WindmillOutputSmallDatasetLoader()

In [446]:
a = loader6.get_dataset()

In [447]:
np.array(a.edge_index).shape

(2, 121)

In [448]:
np.array(a.edge_weight).shape

(121,)

## METRLADatasetLoader_real world traffic dataset

A traffic forecasting dataset based on Los Angeles Metropolitan traffic conditions. The dataset contains traffic readings collected from 207 loop detectors on highways in Los Angeles County in aggregated 5 minute intervals for 4 months between March 2012 to June 2012.

데이터정리 

- T = 33
- V = 구역
- N = 207 # number of nodes 
- E = 225 
- $f(v,t)$의 차원? (3,) # Hourly energy output 
- 시간에 따라서 N이 변하는지? False
- 시간에 따라서 E가 변하는지? False
- X: (207,4) (N,2,12), $x_0,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_{10},x_{11},z_0,z_1,z_2,z_3,z_4,z_5,z_6,z_7,z_8,z_9,z_{10},z_{11}$
- y: (207,) (N,), $(x_{12})$
- 예제코드적용가능여부: No

https://arxiv.org/pdf/1707.01926.pdf

`-` Nodes : `207`

- vertices are localities

`-`Edges : `225`

- edges are spatial_connections

`-` Time : `33`

- between 2020 and 2021
- per weeks

In [464]:
from torch_geometric_temporal.dataset import METRLADatasetLoader
loader7 = METRLADatasetLoader()

In [465]:
a = loader7.get_dataset()

In [466]:
np.array(a.edge_index).shape

(2, 1722)

In [467]:
np.array(a.edge_weight).shape

(1722,)

## PemsBayDatasetLoader

https://onlinelibrary.wiley.com/doi/pdf/10.1111/tgis.12644

A traffic forecasting dataset as described in Diffusion Convolution Layer Paper.

This traffic dataset is collected by California Transportation Agencies (CalTrans) Performance Measurement System (PeMS). It is represented by a network of 325 traffic sensors in the Bay Area with 6 months of traffic readings ranging from Jan 1st 2017 to May 31th 2017 in 5 minute intervals.

데이터정리 

- T = 17470
- V = 풍력발전소
- N = 325 # number of nodes 
- E = 101761 = N^2 # edges 
- $f(v,t)$의 차원? (1,) # Hourly energy output 
- 시간에 따라서 N이 변하는지? False
- 시간에 따라서 E가 변하는지? False
- X: (325,2,12) (N,2,12), 
    - $x_0,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_{10},x_{11}$ 
    - $z_0,z_1,z_2,z_3,z_4,z_5,z_6,z_7,z_8,z_9,z_{10},z_{11}$
- y: (325,) (N,2,12), 
    - $x_{13},x_{14},x_{15},x_{16},x_{17},x_{18},x_{19},x_{20},x_{21},x_{22},x_{23},x_{24}$
    - $z_{13},z_{14},z_{15},z_{16},z_{17},z_{18},z_{19},z_{20},z_{21},z_{22},z_{23},z_{24}$
- 예제코드적용가능여부: No

`-` Nodes : `325`

- vertices are sensors

`-`Edges : `2694`

- weighted edges are between seonsor paris measured by the road nretwork distance

`-` Time : `52081`

- 6 months of traffic readings ranging from Jan 1st 2017 to May 31th 2017 in 5 minute intervals

In [468]:
from torch_geometric_temporal.dataset import PemsBayDatasetLoader
loader8 = PemsBayDatasetLoader()

In [472]:
a = loader8.get_dataset()

In [473]:
np.array(a.edge_index).shape

(2, 2694)

In [474]:
np.array(a.edge_weight).shape

(2694,)

## EnglandCovidDatasetLoader

Covid19 England

- A dataset about mass mobility between regions in England and the number of confirmed COVID-19 cases from March to May 2020 [38]. Each day contains a different mobility graph and node features corresponding to the number of cases in the previous days. Mobility stems from Facebook Data For Good 1 and cases from gov.uk 2

https://arxiv.org/pdf/2009.08388.pdf

데이터정리 

- T = 60
- V = 지역
- N = 129 # number of nodes 
- E = 2158
- $f(v,t)$의 차원? (1,) # 코로나확진자수
- 시간에 따라서 Number of nodes가 변하는지? False
- 시간에 따라서 Number of edge가 변하는지? TRUE
- X: (20,4) (N,4), $f(v,t_0),f(v,t_1),f(v,t_2),f(v,t_3)$
- y: (20,) (N,), $f(v,t_4)$
- 예제코드적용가능여부: Yes

`-` Nodes : `129`

- vertices are correspond to the number of COVID-19 cases in the region in the past window days.

`-`Edges : `2158`

- the spatial edges capture county-to-county movement at a specific date, and a county is connected to a number of past instances of itself with temporal edges.

`-` Time : `61`

- from 3 March to 12 of May

In [475]:
from torch_geometric_temporal.dataset import EnglandCovidDatasetLoader
loader9 = EnglandCovidDatasetLoader()

In [478]:
a = loader9.get_dataset()

In [482]:
a.edge_indices[1]

array([[ 98,  28,  28, ...,  72,  36,  36],
       [ 98, 103,  65, ...,  26,  92,  47]])

In [487]:
a.edge_weights[1]

array([2.02818e+05, 4.97000e+02, 6.90000e+01, ..., 3.80000e+01,
       1.70000e+01, 1.80000e+01])

## MontevideoBusDatasetLoader

https://www.fing.edu.uy/~renzom/msc/uploads/msc-thesis.pdf

Montevideo Buses

- A dataset about the hourly passenger inflow at bus stop level for eleven bus lines from the city of Montevideo. Nodes are bus stops and edges represent connections between the stops; the dataset covers a whole month of traffic patterns.

데이터정리 

- T = 743
- V = 버스정류장 
- N = 675 # number of nodes 
- E = 101761 = N^2 # edges 
- $f(v,t)$의 차원? (1,) # passenger inflow 
- 시간에 따라서 Number of nodes가 변하는지? False
- 시간에 따라서 Number of nodes가 변하는지? False
- X: (675,4) (N,4), $f(v,t_0),f(v,t_1),f(v,t_2),f(v,t_3)$
- y: (675,,) (N,), $f(v,t_4)$
- 예제코드적용가능여부: Yes

`-` Nodes : `675`

- vertices are bus stops

`-`Edges : `690`

- edges are links between bus stops when a bus line connects them and the weight represent the road distance

`-` Time : `743`

-  hourly inflow passenger data at bus stop level for 11 bus lines during October 2020 from Montevideo city (Uruguay).

In [488]:
from torch_geometric_temporal.dataset import MontevideoBusDatasetLoader
loader10 = EnglandCovidDatasetLoader()

In [489]:
a = loader10.get_dataset()

In [490]:
a.edge_indices[1]

array([[ 98,  28,  28, ...,  72,  36,  36],
       [ 98, 103,  65, ...,  26,  92,  47]])

In [491]:
a.edge_weights[1]

array([2.02818e+05, 4.97000e+02, 6.90000e+01, ..., 3.80000e+01,
       1.70000e+01, 1.80000e+01])

## TwitterTennisDatasetLoader

https://appliednetsci.springeropen.com/articles/10.1007/s41109-018-0080-5?ref=https://githubhelp.com

Twitter Tennis RG and UO

- Twitter mention graphs of major tennis tournaments from 2017. Each snapshot contains the graph of popular player or sport news accounts and mentions between them [5, 6]. Node labels encode the number of mentions received and vertex features are structural properties

데이터정리 

- T = 52081
- V = 트위터계정  
- N = 1000 # number of nodes 
- E = 119 = N^2 # edges 
- $f(v,t)$의 차원? (1,) # passenger inflow 
- 시간에 따라서 N이 변하는지? ??
- 시간에 따라서 E가 변하는지? True
- X: ?
- y: ?
- 예제코드적용가능여부: No

`-` Nodes : `1000`

- vertices are Twitter accounts

`-`Edges : `119`

- edges are mentions between them

`-` Time : `52081`

- Twitter mention graphs related to major tennis tournaments from 2017

In [492]:
from torch_geometric_temporal.dataset import TwitterTennisDatasetLoader
loader11 = TwitterTennisDatasetLoader()

In [493]:
a = loader11.get_dataset()

In [494]:
a.edge_indices[1]

array([[218, 218, 205, 205,  84,  84,  84,  84, 135, 135, 140, 140, 140,
        140, 140, 450, 450, 637, 637, 637, 637, 637, 860, 330, 330, 330,
        330, 962, 295, 295, 764, 142, 142, 142, 142, 142, 142, 142, 142,
        295, 160, 312, 312,   9, 801, 801, 265, 265, 265, 551, 551, 551,
        526, 526, 162,  92,  91, 802, 963, 963,   9],
       [  0,   4, 310,   0,   0,   9,  17,  85,   0,  37,   9,  74,   0,
         32,   8, 111, 403,   9, 146,   3,  74,   0,  49,  74,   9,   3,
          0,  13, 248,  96,   0,   0,  31, 119,  52,  62,  24,   7,  86,
        619,   0,   0, 146,   0,   0,   9,   0,   5,  13,   2, 926,   0,
         62,   9,   0,  92, 172,  80,  31,   0, 255]])

In [495]:
a.edge_weights[1]

array([1, 1, 1, 1, 1, 1, 6, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2])

## MTMDatasetLoader

MTM-1 Hand Motions

- A temporal dataset of MethodsTime Measurement-1 [36] motions, signalled as consecutive graph frames of 21 3D hand key points that were acquired via MediaPipe Hands [64] from original RGB-Video material. Node features encode the normalized xyz-coordinates of each finger joint and the vertices are connected according to the human hand structure.

데이터정리 

- T = 14452
- V = 손의 shape에 대응하는 dot    
- N = 325 # number of nodes 
- E = 19 = N^2 # edges 
- $f(v,t)$의 차원? (Grasp, Release, Move, Reach, Poision, -1)
- 시간에 따라서 N이 변하는지? ??
- 시간에 따라서 E가 변하는지? ??
- X: ?
- y: ?
- 예제코드적용가능여부: No

`-` Nodes : `325`

- vertices are are the finger joints of the human hand

`-`Edges : `19`

- edges are the bones connecting them

`-` Time : `14452`

In [496]:
from torch_geometric_temporal.dataset import MTMDatasetLoader
loader12 = MTMDatasetLoader()

In [497]:
a = loader12.get_dataset()

In [501]:
np.array(a.edge_index).shape

(2, 19)

In [503]:
np.shape(a.edge_weight)

(19,)